# Задание 1

In [1]:
import numpy as np

Входные параметры для нейронной сети:
Не ревнивый
Есть работа
Московкая ли прописка
Любит ли кошек
Красивый или нет
Мусорит ли


In [2]:
def act(x):
    return 0 if x < 0.5 else 1


def go_forward(notjel, work, flat, cat, cute, socks):
    x = np.array([notjel, work, flat, cat, cute, socks])
    w11 = [-0.5, 1, 0.4, 0.3, 0.2, -0.3]
    w12 = [0.4, -0.3, -0.5, 0.4, 0.2, 0.3]
    weight1 = np.array([w11, w12])
    weight2 = np.array([-1, 1])
    sum_hidden = np.dot(weight1, x)
    print("Значение суммы на нейронах скрытого слоя: " + str(sum_hidden))
    out_hidded = np.array([act(x) for x in sum_hidden])
    print("Значения на выходах нейронов скрытого слоя: " + str(out_hidded))
    sun_end = np.dot(weight2, out_hidded)
    y = act(sun_end)
    return y

In [3]:
notjel = 0
work = 1
flat = 1
cat = 1
cute = 1
socks = 1

In [4]:
res = go_forward(notjel, work, flat, cat, cute, socks)
if res == 1:
    print("Норм поц")
else:
    print("Не норм")

Значение суммы на нейронах скрытого слоя: [1.6 0.1]
Значения на выходах нейронов скрытого слоя: [1 0]
Не норм


In [5]:
notjel = 1
work = 0
flat = 0
cat = 1
cute = 1
socks = 0

In [6]:
res = go_forward(notjel, work, flat, cat, cute, socks)
if res == 1:
    print("Норм поц")
else:
    print("Не норм")

Значение суммы на нейронах скрытого слоя: [0. 1.]
Значения на выходах нейронов скрытого слоя: [0 1]
Норм поц


# Задание 2

In [7]:
def activate(x):
    return 2 / (1 + np.exp(-x)) - 1


def df(x):
    return 0.5 * (1 + x) * (1 - x)


def go_forward(inp):
    sum = np.dot(W1, inp)
    out = np.array([activate(x) for x in sum])  # запоминаем выходные знечения для каждого нейрона (скрытого слоя)
    sum = np.dot(W2, out)
    y = activate(sum)  # выходное значение для всей нейронной сети
    return y, out


def training(epoch):
    global W2, W1
    lmd = 0.01
    count = len(epoch)
    for k in range(1):
        x = epoch[np.random.randint(0, count)]  # случайный выбор входного сигнала из обучающей выюорки
        y, out = go_forward(x[0:6])  # проход по нейронной сети и вычисление выходных значений нейрона
        e = y - x[-1]  # ошибка
        delta = e * df(y)
        print("\ndelta", delta)
        W2[0][0] = W2[0][0] - lmd * delta * out[0]  # коррекия веса первой связи
        W2[0][1] = W2[0][1] - lmd * delta * out[1]  # коррекия веса второй связи
        delta2 = W2 * delta * df(out)  # вектор

        # коррекция
        W1[0, :] = W1[0, :] - np.array(x[0:6]) * delta2[0][0] * lmd
        W1[1, :] = W1[1, :] - np.array(x[0:6]) * delta2[1][1] * lmd

In [8]:
W1 = np.array([np.random.rand(1, 6), np.random.rand(1, 6)])
W2 = np.random.rand(1, 2)
print("Веса первого слоя до обучения")
print(W1)
print("Веса второго слоя до обучения")
print(W2)

Веса первого слоя до обучения
[[[0.31586486 0.48226138 0.67351007 0.92338966 0.41807905 0.37864384]]

 [[0.45220197 0.94059926 0.80441362 0.34942704 0.90117522 0.99745337]]]
Веса второго слоя до обучения
[[0.47374691 0.47755788]]


In [9]:
# Обучающая выборка
epoch = [(1, 1, 1, 1, 1, 1, 1),
         (0, 0, 1, 1, 1, 0, 0),
         (0, 0, 0, 1, 1, 0, 0),
         (1, 1, 0, 1, 1, 0, 1),
         (1, 0, 0, 1, 1, 1, 1),
         (1, 0, 0, 1, 1, 1, 1),
         (0, 0, 0, 0, 1, 0, 0)]

In [10]:
training(epoch)


delta [[-0.26865382]]


In [11]:
for x in epoch:
    y, out = go_forward(x[0:6])
    print(f"Выходное значение НС:{round(y[0][0], 3)} => {x[-1]}")

print("\nВеса первого слоя после обучения:\n", W1[0][0])
print("\nВеса второго слоя после обучения:\n", W2[0][0])

Выходное значение НС:0.425 => 1
Выходное значение НС:0.352 => 0
Выходное значение НС:0.266 => 0
Выходное значение НС:0.376 => 1
Выходное значение НС:0.374 => 1
Выходное значение НС:0.374 => 1
Выходное значение НС:0.149 => 0

Веса первого слоя после обучения:
 [0.31610576 0.48250228 0.67351007 0.92363056 0.41831996 0.37864384]

Веса второго слоя после обучения:
 0.4758676190421044


In [12]:
test = (1, 0, 1, 0, 0, 1, 1)
y, out = go_forward(test[0:6])
if y[0][0] > 0.3:
    print(f"Норм поц {round(y[0][0], 3)} и {test[-1]}")
else:
    print(f"Не норм {round(y[0][0], 3)} и {test[-1]}")

Норм поц 0.324 и 1


# Задание 3

Постройте нейронную сеть и выполните ее обучение для следующих данных:

In [13]:
def activate(x):
    return 1 / (1 + np.exp(-x))

In [14]:
training_input = np.array([[0, 0, 0, 1],
                           [1, 1, 1, 0],
                           [1, 1, 1, 1],
                           [1, 0, 1, 0],
                           [0, 1, 1, 0],
                           [0, 0, 0, 0]])

training_output = np.array([[0, 1, 1, 0, 1, 0]]).T

In [15]:
np.random.seed(1)
syn_weight = 2 * np.random.random((4, 1)) - 1
print(f"Случайные веса:\n{syn_weight} ")

Случайные веса:
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]
 [-0.39533485]] 


In [16]:
for i in range(20000):
    input_layer = training_input
    output = activate(np.dot(input_layer, syn_weight))
    err = training_output - output
    ad = np.dot(input_layer.T, err * (output * (1 - output)))
    syn_weight += ad

print(f"Веса после обучения:\n{syn_weight} ")

Веса после обучения:
[[-2.28678078]
 [13.94166247]
 [-2.35699105]
 [-4.57590942]] 


In [17]:
new_inp = np.array([0, 1, 0, 0])
new_output = activate(np.dot(new_inp, syn_weight))
print(f"Тестовый прогон: ")

if new_output > 0.90:
    print(f"1: {round(new_output[0], 3)}")
else:
    print(f"0")

Тестовый прогон: 
1: 1.0


In [18]:
new_inp = np.array([1, 0, 1, 1])
new_output = activate(np.dot(new_inp, syn_weight))
print(f"Тестовый прогон: ")

if new_output > 0.90:
    print(f"1: {round(new_output[0], 3)}")
else:
    print(f"0")

Тестовый прогон: 
0
