# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

## Лабораторная работа №1

In [24]:
import numpy as np

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [25]:
data = np.loadtxt('minutes_n_ingredients.csv', delimiter=',',dtype='int32', skiprows=1)

In [26]:
data[:5]

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       [ 67660,      5,      6],
       [157911,     60,     14]], dtype=int32)

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [27]:
max_col2 = np.max(data[:,1])
max_col3 = np.max(data[:,2])

min_col2 = np.min(data[:,1])
min_col3 = np.min(data[:,2])

mean_col2 = np.mean(data[:,1])
mean_col3 = np.mean(data[:,2])

median_col2 = np.median(data[:,1])
median_col3 = np.median(data[:,2])

print('Mean:',mean_col2,mean_col3,'\nMax:',max_col2,max_col3,'\nMin:',min_col2,min_col3,'\nMedian:',median_col2,median_col3)

Mean: 21601.00169 9.05528 
Max: 2147483647 39 
Min: 0 1 
Median: 40.0 9.0


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [28]:
q75 = np.quantile(data[:,1], 0.75)
q75

65.0

In [29]:
data = data[np.where(data[:,1] < q75)]
len(data)

73106

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [30]:
zeros = np.count_nonzero(data[:,1] == 0)
print(f" Вот столько {zeros} пропущенных значений.")

 Вот столько 479 пропущенных значений.


In [31]:
data[:,1] = np.where(data[:,1] == 0 , 1, data[:,1])

5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [32]:
len(np.unique(data[:,0]).tolist())

73106

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [33]:
np.unique(data[:,2]).tolist()

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 33,
 34]

In [34]:
len(np.unique(data[:,2]).tolist())

32

7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [35]:
new_receipts = data[np.where(data[:,2] <= 5)]
print(f" {len(new_receipts)} рецептов с не более 5 ингредиентами.")

 14626 рецептов с не более 5 ингредиентами.


8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [36]:
np.max(np.where(data[:,1] != 0 , data[:,1]/data[:,2], 0))

35.0

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [37]:
sorted_receipts = data[np.argsort(data[:, 1])]
sorted_receipts

array([[359190,      1,      2],
       [269774,      1,      4],
       [  1576,      1,      6],
       ...,
       [141461,     64,     10],
       [200352,     64,     11],
       [265059,     64,     10]], dtype=int32)

In [38]:
print(f'Среднее количество ингредиентов: {np.mean(sorted_receipts[-100:][:,2])}')

Среднее количество ингредиентов: 8.84


10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [39]:
idx = np.arange(data.shape[0])
mask = np.zeros_like(idx, dtype=bool)
mask[np.random.choice(idx, 10, replace=False)] = True

data[mask]

array([[ 47250,     26,     11],
       [242434,     30,     12],
       [108301,     21,      7],
       [377054,     17,      5],
       [233732,      1,      6],
       [344796,     60,     11],
       [258913,     45,      3],
       [ 50223,     27,     14],
       [116582,     36,     12],
       [422152,     30,      9]], dtype=int32)

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [40]:
cnt_receipts = len(sorted_receipts[np.where(sorted_receipts[:,2] < np.mean(sorted_receipts[-100:][:,2]))])
print(f'{round(cnt_receipts/len(sorted_receipts)*100,2)}% рецептов, кол-во ингредиентов в которых меньше среднего ')

52.98% рецептов, кол-во ингредиентов в которых меньше среднего 


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [41]:
sorted_receipts

array([[359190,      1,      2],
       [269774,      1,      4],
       [  1576,      1,      6],
       ...,
       [141461,     64,     10],
       [200352,     64,     11],
       [265059,     64,     10]], dtype=int32)

In [42]:
b = np.zeros(len(data),dtype='int32')
b[(data[:,1]<=20) & (data[:,2]<=5)] = 1
data_with_4_column = np.insert(data, 3, b, axis=1)
data_with_4_column

array([[127244,     60,     16,      0],
       [ 23891,     25,      7,      0],
       [ 94746,     10,      6,      0],
       ...,
       [371794,     35,      8,      0],
       [ 43407,     35,      7,      0],
       [370915,      5,      4,      1]], dtype=int32)

13. Выведите процент "простых" рецептов в датасете

In [43]:
simple_receipts = new_receipts[np.where(new_receipts[:,1] <= 20)]
print(f'{round(len(simple_receipts)/len(data)*100,2)}% простых рецептов')

13.07% простых рецептов


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [44]:
receipts_ticket = np.zeros(len(data),dtype='int32')
receipts_ticket[data[:,1]<10] = 1
receipts_ticket[(data[:,1]>=10) & (data[:,1]<20)] = 2
receipts_ticket[(data[:,1]>=20)] = 3

In [45]:
data_with_tickets = np.insert(data, 3, receipts_ticket, axis=1)
print(f'Кол-во рецептов по признаку:\nКороткие: {len(data_with_tickets[data_with_tickets[:,3]==1])}\nСтандартные: {len(data_with_tickets[data_with_tickets[:,3]==2])}\nДлинные: {len(data_with_tickets[data_with_tickets[:,3]==3])}')

Кол-во рецептов по признаку:
Короткие: 7588
Стандартные: 12661
Длинные: 52857


In [46]:
short = data_with_tickets[data_with_tickets[:,3]==1]
standart = data_with_tickets[data_with_tickets[:,3]==2][:7588]
long = data_with_tickets[data_with_tickets[:,3]==3][:7588]